'use client'

import Head from 'next/head'
import { LocalizationProvider } from '@mui/x-date-pickers'
import { AdapterMoment } from '@mui/x-date-pickers/AdapterMoment'
import { Box } from '@mui/material'
import Header from '@/component/header'
import Calendar from '@/component/calendar/calendar'

export default function Home() {
  return (
    <>
      <Head>
        <title>ALR 91 - Dashboard</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Box component='main' sx={{ display: 'flex', flexDirection: 'column', height: '100vh' }}>
        <Header />
        <LocalizationProvider dateAdapter={AdapterMoment}>
          <Calendar flexGrow={1} maxHeight='calc(100vh - 64px)' />
        </LocalizationProvider>
      </Box>
    </>
  )
}
//635 - 580
